### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tokufxug** [magic-script/magic-script-samples#22]
An error occurs when building.

C:\MagicScript\sample-model>magic-script build -i
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/creationix/rollup-plugin-commonjs.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<<USER_NAME>>\AppData\Roaming\npm-cache\_logs\2019-03-30T20_13_22_207Z-debug.log
C:\Users\<<USER_NAME>>\AppData\Roaming\npm\node_modules\magic-script-cli\commands\build.js:15
        throw err;
        ^

Error: Command failed: npm install
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/creationix/rollup-plugin-commonjs.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<<USER_NAME>>\AppData\Roaming\npm-cache\_logs\2019-03-30T20_13_22_207Z-debug.log

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

C:\MagicScript\sample-model>

-------------------------------------------------------------
Windows 10 Version 1803(OS build 17134.648)
NodeJS v11.10.0
npm v6.9.0
Lumin SDK v0.20.0
magic-script-cli v.1.0.3

Thanks

**Comment by kpiascik** [comment]
Hey @tokufxug  I tried to reproduce on my windows machine but didn't see any problems.
I'm using:
NodeJS V10.12.0
npm v6.4.1

Can you check that you have access to https://github.com/creationix/rollup-plugin-commonjs.git since it's the failing depencency.

**Comment by leoz** [comment]
Hi Sadao-san (@tokufxug) ,

I've tried to reproduce it on my personal MS Windows laptop, but it did work as intended.

The steps I've performed are:

1. install MxS CLI:

npm install -g magic-script-cli

2. Install Lumin SDK and Lumin Runtime SDK

3. Generate and download certificate

4. Set-up env:

%USERPROFILE%/MagicLeap/mlsdk/v0.20.0/envsetup.bat

SET MLCERT=<path to cert>

5. Install dependencies:

cd sample-model
npm i

6. Execute build step:

magic-script build

Could you try to repeat these steps?

Leonid.

node v10.15.2
npm 6.9.0
magic-script 1.0.3

**Comment by tokufxug** [comment]
The problem that can not be built has been resolved.

_**0.**_ I uninstalled NodeJS v11.10.0 and installed NodeJS v.10.15.3. 
   - Manually delete the following
     - %USERPROFILE%\AppData\Roaming\npm 
     - %USERPROFILE%\AppData\Roaming\npm-cache
     - Also reinstall magic-script.


**1.** Set "C:\PythonXX\Scripts" to user environment variable. (XX is the version number. Have Python installed)
**2.** Install and set up the following because rollup-plugin-commonjs is required.
   - Install Git for Windows (https://gitforwindows.org/)
   - Set Git as a User Environment Variable.

**3.** PC restart.
**4.** npm install --save-dev rollup-plugin-commonjs
**5.** magic-script build -i

Thanks.

node v10.15.3
npm 6.4.1
magic-script 1.0.3

Sadao Tokuyama
[https://twitter.com/tokufxug](https://twitter.com/tokufxug)
